# Generated by Django 6.0.2 on 2026-03-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_due_date_assignment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_submission_policy',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('penalty', 'Allow with penalty')], default='deny', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_penalty_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubmissionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
