# Generated by Django 5.1.7 on 2026-03-23 05:50

from django.db import migrations, models
import uuid


def generate_join_keys(apps, schema_editor):
    """Generate unique join keys for all existing classrooms"""
    Classroom = apps.get_model('classrooms', 'Classroom')
    for classroom in Classroom.objects.all():
        classroom.join_key = str(uuid.uuid4())[:8].upper()
        classroom.save()


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='join_key',
            field=models.CharField(default='', editable=False, max_length=8),
        ),
        migrations.RunPython(generate_join_keys),
        migrations.AlterField(
            model_name='classroom',
            name='join_key',
            field=models.CharField(default='', editable=False, max_length=8, unique=True),
        ),
    ]
