# Generated by GitHub Copilot on 2026-03-29

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def set_default_join_key_expiry(apps, schema_editor):
    Classroom = apps.get_model('classrooms', 'Classroom')
    now = timezone.now()
    default_expires_at = now + timedelta(minutes=60)
    Classroom.objects.filter(join_key_expires_at__isnull=True).update(join_key_expires_at=default_expires_at)


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_classroom_created_at_classroom_join_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_join_key_expiry, migrations.RunPython.noop),
    ]
