# Generated by Django 6.0.2 on 2026-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_classroom_join_key_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_key_ttl_override_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='joins_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
