# Generated by Django 6.0.2 on 2026-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_lecture_updated_at_lecturecomment_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_thread_locked',
            field=models.BooleanField(default=False),
        ),
    ]
