# Generated by Django 6.0.2 on 2026-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_notice_updated_at_noticecomment_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_thread_locked',
            field=models.BooleanField(default=False),
        ),
    ]
